language: objective-c
script:
  - xctool -project 'TransformTest.xcodeproj' -scheme 'All' ONLY_ACTIVE_ARCH=NO
  - xctool test -project 'TransformTest.xcodeproj' -scheme 'Unit Tests' ONLY_ACTIVE_ARCH=NO
